// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtcARquetK59od8KQgzmk-UiO5AEHsj2g',
    appId: '1:34880895534:web:572a26d4d778a0d6d57dbf',
    messagingSenderId: '34880895534',
    projectId: 'vintedia2-b311e',
    authDomain: 'vintedia2-b311e.firebaseapp.com',
    storageBucket: 'vintedia2-b311e.appspot.com',
    measurementId: 'G-6DP714R69E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-nKjEjvMDhXG32_c2IfMMHlcFq2eP-A',
    appId: '1:34880895534:android:30caa664755952a5d57dbf',
    messagingSenderId: '34880895534',
    projectId: 'vintedia2-b311e',
    storageBucket: 'vintedia2-b311e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9FVAxiS5rdqWwaOvdMlQ6vGddydQYMlM',
    appId: '1:34880895534:ios:310ca43f049dde74d57dbf',
    messagingSenderId: '34880895534',
    projectId: 'vintedia2-b311e',
    storageBucket: 'vintedia2-b311e.appspot.com',
    iosBundleId: 'com.example.vintedia2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9FVAxiS5rdqWwaOvdMlQ6vGddydQYMlM',
    appId: '1:34880895534:ios:310ca43f049dde74d57dbf',
    messagingSenderId: '34880895534',
    projectId: 'vintedia2-b311e',
    storageBucket: 'vintedia2-b311e.appspot.com',
    iosBundleId: 'com.example.vintedia2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtcARquetK59od8KQgzmk-UiO5AEHsj2g',
    appId: '1:34880895534:web:0178d29272a9b119d57dbf',
    messagingSenderId: '34880895534',
    projectId: 'vintedia2-b311e',
    authDomain: 'vintedia2-b311e.firebaseapp.com',
    storageBucket: 'vintedia2-b311e.appspot.com',
    measurementId: 'G-KWZ7NB0ZPV',
  );
}
